import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Factory,Layers,ChevronRight,GitCompareArrows,Building2,Dumbbell,Weight,Ruler,Box,CircleDollarSign,CreditCard,Clock,Package,Settings,Palette,Shield,Tag,Users,MapPin,Info,Printer, type LucideIcon} from 'lucide-react';
import {Badge} from './components/ui/badge';
import {Button} from './components/ui/button';
import {Card,CardHeader,CardTitle,CardContent,CardFooter} from './components/ui/card';
import {Tabs,TabsList,TabsTrigger,TabsContent} from './components/ui/tabs';
import {displayValue,fieldLabel,classLabel,applicationLabel,capitalize} from './vocabulary';
interface Evidence{field:string;value:string;source_section:string}
interface Variant{field:string;values:{value:string;source_section:string;declared_class:string|null}[]}
interface Extraction{product:{name:string|null;brand:string|null;model:string|null};specifications:Evidence[];commercial_terms:Evidence[];images:{url:string;alt:string|null}[];contextual_variants:Variant[];usage_classification:{declared_class:string|null;classified_applications:string[]}}
const icons:Record<string,LucideIcon>={tube_size:Settings,tube_thickness:Settings,weight_stack:Weight,dimensions:Ruler,packing_dimensions:Box,packing_type:Package,net_weight:Weight,gross_weight:Weight,price:CircleDollarSign,moq:Package,payment_terms:CreditCard,delivery_time:Clock,after_sales:Settings,material:Layers,declared_certifications:Shield,model:Tag,brand:Factory,color:Palette,frame_color:Palette,cushion_color:Palette,appliance:Building2,application:Building2,max_user_weight:Users,origin:MapPin};
function LabelBadge({field,variant='secondary'}:{field:string;variant?:'secondary'|'outline'|'default'}){const Icon=icons[field]??Info;return <Badge variant={variant}><Icon data-icon="inline-start"/>{fieldLabel(field)}</Badge>}
function FieldCards({records}:{records:Evidence[]}){const groups=new Map<string,string[]>();for(const r of records){const text=displayValue(r.field,r.value);if(!text)continue;const values=groups.get(r.field)??[];if(!values.includes(text))values.push(text);groups.set(r.field,values);}return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{[...groups].map(([field,values])=><Card key={field}><CardHeader><CardTitle><LabelBadge field={field}/></CardTitle></CardHeader><CardContent className="flex flex-col gap-3">{values.map(value=><p key={value} className="text-sm leading-relaxed">{capitalize(value)}</p>)}</CardContent></Card>)}</div>}
function App({data}:{data:Extraction}){
 const [photo,setPhoto]=useState(0);const [tab,setTab]=useState('technical');const usage=data.usage_classification;
 const name=displayValue('name',data.product.name??'')??'Equipamento';
 const values=(field:string)=>[...new Set(data.specifications.filter(r=>r.field===field).map(r=>displayValue(field,r.value)).filter((r):r is string=>r!==null))];
 const contextual=new Set(data.contextual_variants.map(x=>x.field));
 return <div className="min-h-screen"><header className="border-b bg-card"><div className="mx-auto flex max-w-[1600px] items-center justify-between gap-4 px-5 py-4 lg:px-8"><a href="/" className="flex items-center gap-3"><div className="flex size-10 items-center justify-center rounded-xl bg-primary text-primary-foreground"><Factory className="size-5"/></div><div><p className="font-semibold">Catálogo de equipamentos</p><p className="text-xs text-muted-foreground">Engenharia e soluções para academias</p></div></a><Button variant="outline" size="sm" onClick={()=>window.print()}><Printer data-icon="inline-start"/>Imprimir ficha</Button></div></header>
 <div className="mx-auto grid max-w-[1600px] lg:grid-cols-[230px_minmax(0,1fr)]"><aside className="border-b p-5 lg:min-h-screen lg:border-r lg:border-b-0"><Badge variant="outline"><Factory data-icon="inline-start"/>Fábricas</Badge><div className="mt-5"><Badge><Factory data-icon="inline-start"/>BRTW</Badge></div><div className="mt-6 flex flex-col items-start gap-3 border-l pl-4"><Badge variant="secondary"><Layers data-icon="inline-start"/>Série HS · 2025</Badge><a href="#machine" className="rounded-lg bg-accent px-3 py-3 text-sm font-semibold text-accent-foreground">HS01 · {name}</a></div></aside>
 <main className="flex min-w-0 flex-col gap-6 p-5 lg:p-8"><nav aria-label="Localização" className="flex flex-wrap items-center gap-2 text-xs text-muted-foreground"><span>Fábricas</span><ChevronRight className="size-3"/><span>BRTW</span><ChevronRight className="size-3"/><span>Série HS</span><ChevronRight className="size-3"/><span>HS01</span></nav>
 <div id="machine" className="flex flex-wrap items-end justify-between gap-4"><div><div className="mb-3 flex flex-wrap gap-2"><Badge><Tag data-icon="inline-start"/>{data.product.model??'Modelo'}</Badge><Badge variant="secondary"><Layers data-icon="inline-start"/>Série HS · 2025</Badge><Badge variant="outline"><Dumbbell data-icon="inline-start"/>{classLabel(usage.declared_class)}</Badge></div><h1 className="text-3xl font-semibold md:text-4xl">{name}</h1></div><Button variant="outline" onClick={()=>setTab('classes')}><GitCompareArrows data-icon="inline-start"/>Comparar classes</Button></div>
 <div className="grid gap-5 xl:grid-cols-[minmax(0,1.2fr)_minmax(0,1fr)]"><Card><CardHeader><CardTitle><Badge variant="outline"><Dumbbell data-icon="inline-start"/>Equipamento</Badge></CardTitle></CardHeader><CardContent><img className="h-96 w-full object-contain" src={data.images[photo]?.url} alt={`BRTW HS01 · ${name}`}/></CardContent><CardFooter className="gap-2">{data.images.map((img,i)=><Button key={img.url} variant={photo===i?'secondary':'outline'} onClick={()=>setPhoto(i)} aria-label={`Ver foto ${i+1}`} aria-pressed={photo===i}><img src={img.url} alt="" className="size-9 object-contain"/>Foto {i+1}</Button>)}</CardFooter></Card>
 <div className="flex flex-col gap-5"><Card><CardHeader><CardTitle><Badge><Dumbbell data-icon="inline-start"/>{classLabel(usage.declared_class)}</Badge></CardTitle></CardHeader><CardContent className="flex flex-wrap gap-2">{usage.classified_applications.map(a=><Badge key={a} variant="outline"><Building2 data-icon="inline-start"/>{applicationLabel(a)}</Badge>)}</CardContent></Card><div className="grid grid-cols-2 gap-4">{['net_weight','gross_weight'].map(field=><Card key={field}><CardHeader><CardTitle><LabelBadge field={field}/></CardTitle></CardHeader><CardContent><p className="text-2xl font-semibold">{values(field).join(' · ')||'Não informado'}</p></CardContent></Card>)}</div><Card><CardHeader><CardTitle><LabelBadge field="packing_dimensions"/></CardTitle></CardHeader><CardContent className="flex flex-col gap-3"><p className="text-xl font-semibold">{values('packing_dimensions').join(' · ')||'Não informado'}</p><Badge variant="outline"><Package data-icon="inline-start"/>{values('packing_type').join(' · ')||'Embalagem não informada'}</Badge></CardContent></Card></div></div>
 <div className="grid gap-4 md:grid-cols-3">{data.contextual_variants.map(group=><Card key={group.field}><CardHeader><CardTitle><LabelBadge field={group.field}/></CardTitle></CardHeader><CardContent className="flex flex-col gap-4">{group.values.map((r,i)=>{const text=displayValue(group.field,r.value);return text?<div key={i} className="flex flex-col items-start gap-2"><Badge variant="outline"><Settings data-icon="inline-start"/>{group.field==='weight_stack'?'Carga':'Medida'} {i+1}</Badge><p className="text-xl font-semibold">{text}</p></div>:null;})}</CardContent></Card>)}</div>
 <Tabs value={tab} onValueChange={setTab} className="gap-5"><div className="overflow-x-auto"><TabsList><TabsTrigger value="technical"><Settings/>Ficha técnica</TabsTrigger><TabsTrigger value="classes"><GitCompareArrows/>Classes de uso</TabsTrigger><TabsTrigger value="commercial"><CreditCard/>Condições comerciais</TabsTrigger></TabsList></div><TabsContent value="technical"><FieldCards records={data.specifications.filter(r=>!contextual.has(r.field)&&!['model','name','brand','net_weight','gross_weight','packing_dimensions','packing_type'].includes(r.field))}/></TabsContent>
 <TabsContent value="classes"><div className="grid gap-4 md:grid-cols-2"><Card><CardHeader><CardTitle><Badge variant="secondary"><Building2 data-icon="inline-start"/>Comercial leve</Badge></CardTitle></CardHeader><CardContent className="flex flex-wrap gap-2"><Badge variant="outline"><Building2 data-icon="inline-start"/>Estúdios</Badge><Badge variant="outline"><Building2 data-icon="inline-start"/>Condomínios</Badge><Badge variant="outline"><Clock data-icon="inline-start"/>Uso moderado</Badge></CardContent></Card><Card><CardHeader><CardTitle><Badge><Dumbbell data-icon="inline-start"/>Comercial</Badge></CardTitle></CardHeader><CardContent className="flex flex-wrap gap-2"><Badge variant="outline"><Building2 data-icon="inline-start"/>Academias</Badge><Badge variant="outline"><Clock data-icon="inline-start"/>Uso frequente</Badge><Badge variant="outline"><Tag data-icon="inline-start"/>HS01</Badge></CardContent></Card></div></TabsContent>
 <TabsContent value="commercial"><FieldCards records={data.commercial_terms}/></TabsContent></Tabs>
 <footer className="flex flex-wrap items-center justify-between gap-3 py-4"><Badge variant="outline"><Factory data-icon="inline-start"/>BRTW</Badge><Badge variant="outline"><Layers data-icon="inline-start"/>Série HS · 2025</Badge></footer></main></div></div>;
}
async function boot(){const root=createRoot(document.getElementById('root')!);try{const response=await fetch('/examples/brtw-hs01.json');if(!response.ok)throw new Error('Não foi possível carregar o equipamento.');const data:Extraction=await response.json();root.render(<App data={data}/>);}catch(error){root.render(<p role="alert">{error instanceof Error?error.message:'Equipamento indisponível.'}</p>);}}
void boot();
