export const vocabulary = {
  classes:{commercial:'Comercial',light_commercial:'Comercial leve'},
  applications:{gym:'Academia',studio:'Estúdio',condominium:'Condomínio',home:'Residencial',hotel:'Hotel',community:'Comunidade'},
  fields:{model:'Modelo',name:'Equipamento',brand:'Marca',age_group:'Faixa etária',gender:'Público',exercise_part:'Grupo muscular',material:'Material',declared_certifications:'Certificações',appliance:'Aplicações',application:'Aplicações',packing_dimensions:'Dimensões da embalagem',packing_type:'Embalagem',tube_size:'Tubulação',tube_thickness:'Espessura dos tubos',dimensions:'Dimensões',weight_stack:'Torre de pesos',micro_minor_adjustment:'Ajuste adicional',net_weight:'Peso líquido',gross_weight:'Peso bruto',max_user_weight:'Peso máximo do usuário',logo:'Personalização da marca',frame_color:'Cor da estrutura',cushion_color:'Cor do estofado',trade_mark:'Marca personalizada',transport_package:'Embalagem de transporte',origin:'Local de fabricação',hs_code:'Código aduaneiro',production_capacity:'Capacidade de produção',features:'Características',color:'Cores',price:'Preço',moq:'Pedido mínimo',payment_terms:'Pagamento',delivery_time:'Prazo de entrega',after_sales:'Pós-venda',faq_q5:'Planejamento do espaço',faq_q6:'Montagem'},
  terms:{MOQ:{label:'Pedido mínimo',meaning:'Quantidade mínima aceita por pedido. Não representa a capacidade mínima de fabricação.'},'T/T':{label:'Transferência bancária',meaning:'Pagamento por transferência bancária.'},'L/C':{label:'Carta de crédito',meaning:'Pagamento por carta de crédito; preservar a condição à vista quando informada.'},SKU:{label:'Modelo',meaning:'Identificador comercial do equipamento.'},packing_size:{label:'Dimensões da embalagem',meaning:'Medidas do equipamento acondicionado para transporte.'}}
} as const;
export function capitalize(value:string){return value?value[0].toLocaleUpperCase('pt-BR')+value.slice(1):value;}
export function fieldLabel(field:string){return vocabulary.fields[field as keyof typeof vocabulary.fields]??'Informação complementar';}
export function classLabel(value:string|null){return vocabulary.classes[value as keyof typeof vocabulary.classes]??'Classe não informada';}
export function applicationLabel(value:string){return vocabulary.applications[value as keyof typeof vocabulary.applications]??'Aplicação não informada';}
const translations:Record<string,string>={
 'Chest Press':'Supino sentado','Adult':'Adulto','Unisex':'Unissex','Chest':'Peitoral','Steel':'Aço','Plywood Box':'Caixa de compensado','Shandong, China':'Shandong, China','Customized Logo Availabled':'Marca personalizada','Customised':'Personalizável','More Colors for Choice or Customised':'Cores disponíveis ou personalizadas','Available':'Disponível','Green, yellow, or customized':'Verde, Amarelo ou personalizado','Professional gym club/Fitness center':'Academia e centro de treinamento','Community, Gymnasium, Home':'Comunidade, Academia e residência'
};
// Product presentation is deliberately separate from collected evidence.
// Unsupported wording is omitted instead of leaking untranslated text or inventing a value.
export function displayValue(field:string,raw:string):string|null {
 if(translations[raw])return translations[raw];
 if(['model','brand','hs_code','declared_certifications'].includes(field))return raw;
 if(['dimensions','packing_dimensions','tube_size','tube_thickness','weight_stack','net_weight','gross_weight','max_user_weight'].includes(field)&&/^[\d\s.,*x×+a-z()-]+$/i.test(raw))return raw.replace(/kgs?\b/gi,'kg').replace(/(?<=\d)\.(?=\d)/g,',').replace(/\s*[*x×]\s*/g,' × ').replace(/(?<=\d)(mm|kg)/g,' $1').replace(/\s*\+\s*/g,' + ');
 if(field==='micro_minor_adjustment'){const weight=raw.match(/\d+(?:\.\d+)?\s*kg/i)?.[0];return weight?'Sim, '+weight.replace('.',',').replace(/(?<=\d)kg/,' kg'):null;}
 if(field==='production_capacity'){const count=raw.match(/([\d,]+)\s*Pieces\s*Monthly/i)?.[1];return count?`${Number(count.replaceAll(',','')).toLocaleString('pt-BR')} unidades por mês`:null;}
 if(field==='price'){const amounts=[...raw.matchAll(/\d+(?:,\d{3})*(?:\.\d+)?/g)].map(x=>Number(x[0].replaceAll(',','')).toLocaleString('pt-BR',{minimumFractionDigits:2}));return amounts.length&&raw.includes('US$')?'US$ '+amounts.join(' – '):null;}
 if(field==='moq'){const count=raw.match(/\d+/)?.[0]??(/\bOne\b/i.test(raw)?'1':null);if(!count)return null;return /set/i.test(raw)?`${count} ${count==='1'?'conjunto':'conjuntos'}${/big strength/i.test(raw)?' para equipamentos de força':''}`:/piece/i.test(raw)?`${count} unidades`:null;}
 if(field==='delivery_time'){const period=raw.match(/(\d+)\s*[-–]\s*(\d+)\s*days/i);if(!period)return null;return `${period[1]} a ${period[2]} dias`+(/deposit received/i.test(raw)?' após confirmação do pedido e recebimento da entrada':/order quantities/i.test(raw)?', conforme a quantidade do pedido. Estruturas disponíveis para algumas séries.':'');}
 if(field==='payment_terms'){const methods=[];if(/T\/T/i.test(raw))methods.push('Transferência bancária');if(/WESTERN UNION/i.test(raw))methods.push('Western Union');if(/L\/C/i.test(raw))methods.push('Carta de crédito'+(/at sight/i.test(raw)?' à vista':''));if(!methods.length)return null;const deposit=raw.match(/(\d+)%\s*(?:as\s+)?deposit/i)?.[1];const minimum=/at least/i.test(raw)?' mínima':'';const balance=raw.match(/(\d+)%\s*balance/i)?.[1];return methods.join(' · ')+(deposit?`. Entrada${minimum} de ${deposit}%`:'')+(/balance before|balance.*before/i.test(raw)?`; ${balance?'saldo de '+balance+'%':'saldo'} antes do embarque.`:'.');}
 if(field==='after_sales'&&/2%/.test(raw)&&/replacement for free/i.test(raw))return 'Peças de desgaste adicionais equivalentes a 2% e reposição gratuita de peças danificadas durante a garantia.';
 if(field==='faq_q5'&&/Sure.*experience/i.test(raw))return 'Assessoria para planejamento do espaço da academia.';
 if(field==='faq_q6'&&/videos.*pictures.*Label/i.test(raw))return 'Orientações de montagem com vídeos, imagens e peças identificadas.';
 if(field==='features'&&/Q235/i.test(raw)&&/60x100x3mm/i.test(raw))return 'Aço Q235; tubos de 60 × 100 × 3 mm; acabamento pintado; soldagem lisa; desenho próprio; equipamento com carga por anilhas.';
 return null;
}
